
const inquirer=require('inquirer');
const fs=require('fs');
const util=require('util');

// write readme file using promisify method
const writeReadmefileAsync=util.promisify(fs.writeFile);

const promptUser=() =>{
    return inquirer.prompt([
        {
            type: 'input',
            name: 'title',
            message: 'What is the project title?',
        },
        {
            type: 'input',
            name: 'description',
            message: 'Please give description of your project?',
        },

        {
            type: 'input',
            name: 'Installation',
            message: 'What are the steps required to install your project?',
        },
        {

            type: 'input',
            name: 'usage',
            message: 'Enter usage information for the project?',
        },
        {
            type: "list",
            message: "Which license does this project fall under?",
            name: "license",
            choices: [
                "Apache",
                "Academic",
                "GNU",
                "ISC",
                "MIT",
                "Mozilla",
                "Open"
            ],
        },
        {
            type: 'input',
            name: 'contribution',
            message: 'Please add contributors?',
        },
        {
            type: 'input',
            name: 'testInstruction',
            message: 'What command do you use to test the project?',
        },
        {
            type: 'input',
            name: 'questions',
            message: 'What do I do if have error?',
        },
        {
            type: "input",
            name: "username",
            message: "Please enter your GitHub username: "
        },
        {
            type: "input",
            name: "email",
            message: "Please enter your email: "
        }
        
    ])
}
const generateReadMe=(answers)=>

 `
# <h1 align="center"> ${answers.title}</h1>
![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)<br />

## Description
${answers.description}

## Table of Contents
* [Installation](#installation)
* [Usage](#usage)
* [License](#license)
* [Tests](#Tests)
* [Contribution](#Contribution)
* [Questions](#Questions)

            
## Installation
${answers.Installation}
    
        
## Usage
${answers.usage}

## License

![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)<br />
This application is covered by the ${answers.license} license. 

## Contribution
${answers.contribution}

## Tests
${answers.testInstruction}

## Questions
${answers.questions}
Find me on Github: [${answers.username}]
Email me with any questions: ${answers.email}
_This README was generated by [READme generator]()

`

const init = () => {
    promptUser() 
   .then ((answers) => writeReadmefileAsync('./dist/README.md', generateReadMe(answers)))
   .then(() => console.log('Successfully wrote to README.md'))
   .catch((err) => console.error(err));
}

init();
