
const inquirer=require('inquirer');
const fs=require('fs');
const util=require('util');
const generateMarkdown=require("./utils/generateMarkdown")
// write readme file using promisify method
const writeReadmefileAsync=util.promisify(fs.writeFile);
// array of questions for the users
const promptUser=() =>{
    return inquirer.prompt([
        {
            type: 'input',
            name: 'title',
            message: 'What is the project title?',
        },
        {
            type: 'input',
            name: 'description',
            message: 'Please give description of your project?',
        },

        {
            type: 'input',
            name: 'Installation',
            message: 'What are the steps required to install your project?',
        },
        {

            type: 'input',
            name: 'usage',
            message: 'Enter usage information for the project?',
        },
        {
            type: "list",
            message: "Which license does this project fall under?",
            name: "license",
            choices: [
                "Apache",
                "Academic",
                "GNU",
                "ISC",
                "MIT",
                "Mozilla",
                "Open"
            ],
        },
        {
            type: 'input',
            name: 'contribution',
            message: 'Please add contributors?',
        },
        {
            type: 'input',
            name: 'testInstruction',
            message: 'What command do you use to test the project?',
        },
        
        {
            type: "input",
            name: "username",
            message: "Please enter your GitHub username: "
        },
        {
            type: "input",
            name: "email",
            message: "Please enter your email: "
        }
        
    ])
}
const generateReadMe=(answers)=>

 `
# <h1 align="center"> ${answers.title}</h1>
![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)<br />

## Description
${answers.description}

## Table of Contents
* [Installation](#installation)
* [Usage](#usage)
* [License](#license)
* [Tests](#Tests)
* [Contribution](#Contribution)
* [Questions](#Questions)

            
## Installation
${answers.Installation}
    
        
## Usage
${answers.usage}

## License

![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)<br />
This application is covered by the ${answers.license} license. 

## Contribution
${answers.contribution}

## Tests
${answers.testInstruction}

## Questions
For any questions, please contact me with the information below:

Find me on Github: [${answers.username}]<br />
Email me with any questions: ${answers.email}<br />
_This README was generated by [READme generator](https://github.com/KannaVairavan/ReadmeGenerator.git)

`
// function to initialize program
const init = () => {
    promptUser() 
    // create markdown file

   .then ((data) => writeReadmefileAsync('./dist/README.md', generateMarkdown(data)))
   .then(() => console.log('Successfully wrote to README.md'))
   .catch((err) => console.error(err));
}
        // async function init(){
        //     try{
        //         const data = await promptUser();
        //         const generateReadMeContent=generateMarkdown(data);
        //         await writeReadmefileAsync('./dist/README.md', generateReadMeContent);
        //         console.log('Successfully wrote to README.md')
        //     } catch(err){
        //         console.log(err);
        //     }
        // }
// function call to initialize program
init();
