// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {

}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `# ${data.title}
  <hr>
  ![badge](https://img.shields.io/badge/license-${data.license}-brightgreen)<br />
  
  ## Description
  ${data.description}
  
  ## Table of Contents
  * [Installation](#installation)
  * [Usage](#usage)
  * [License](#license)
  * [Tests](#Tests)
  * [Contribution](#Contribution)
  * [Questions](#Questions)
  
              
  ## Installation
  ${data.Installation}
      
          
  ## Usage
  ${data.usage}
  
  ## License
  
  ![badge](https://img.shields.io/badge/license-${data.license}-brightgreen)<br />
  This application is covered by the ${data.license} license. 
  
  ## Contribution
  ${data.contribution}
  
  ## Tests
  ${data.testInstruction}
  
  ## Questions
  For any questions, please contact me with the information below:
  
  Find me on Github: [${data.username}]<br />
  Email me with any questions: ${data.email}<br />
  _This README was generated by [READme generator](https://github.com/KannaVairavan/ReadmeGenerator.git)
  
  `;
}

module.exports = generateMarkdown;
